### ISSUE TITLE
Sugestões de tópicos a serem discutidos

### ISSUE THREAD

**Issue by ythecombinator** [jefponte/MinicursoOOComJava#1]
Primeiramente, parabéns pela iniciativa de promover o curso 🎆–iniciativas assim realmente fazem falta na eng. 

Agora, posso estar enganado–afinal, só tem alguns detalhes da ementa aqui, fora que nem estou no curso 😂 –mas há alguns pontos que eu penso serem válidos de inclusão–ou remoção/alteração–e acho massa levantar a discussão. São eles:

#### Objetos

Por incrível que pareça, muitas vejo que há definições muito superficiais–sim, ocorreu na minha cadeira de *POO* haha–e **objetos** acabam entrando na roda; o que é bem triste, pois, ao meu ver, são um conceito tão importante quanto a passagem de mensagens. 

E assim, temos:

> [...]
    5. Classe, Instância de **Objetos**.
    [...]

O que me leva a pensar que tu vai abordar o conceito. Mas também temos:

> Justificativas: Os conceitos do paradigma da orientação a objetos são obrigatórios para diversos cursos. **A linguagem Java utiliza muito bem esses conceitos**, além de ser amplamente utilizada.

E, se pegarmos uma definição como [a de William Cook](http://wcook.blogspot.com.br/2012/07/proposal-for-simplified-modern.html), temos:

> An object is a first-class, dynamically dispatched behavior. A behavior is a collection of named operations that can be invoked by clients where the operations may share additional hidden details. Dynamic dispatch means that different objects can implement the same operation name(s) in different ways, so the specific operation to be invoked must come from the object identified in the client's request. First class means that objects have the same capabilities as other kinds of values, including being passed to operations or returned as the result of an operation.

Assim, temos que, em uma linguagem rigorosamente OO–onde **tudo é um objeto**–todas as construções sintáticas desta devem seguir a definição acima. Isto é:

- `1` deve ser um comportamento de primeira classe, dinamicamente despachado
- `"foo"` também. 

Mas há outros dois pontos importantes: 

- `boolean`, `byte`, `char`, `short`, `int`, `long`, `float` e `double` **não são objetos**! São [tipos primitivos](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html) que são–a partir do *Java 5*, salvo engano meu–[automaticamente encapsulados](http://docs.oracle.com/javase/1.5.0/docs/guide/language/autoboxing.html); ou seja, convertidos em suas respectivas *"forma de objeto"*, quando você interage com eles. Mas isso significa que tais valores, ao contrário de outros objetos na linguagem, não herdam de `java.lang.Object` nem podem carregar estado.
- Isso também nos restringe de construções como `if`s, `while`s, e seus semelhantes, uma vez que não se dão como mensagens / métodos de um objeto.

Então, eu acho válido deixar isso como adendo a afirmação de que:

> [...] **A linguagem Java utiliza muito bem esses conceitos** [...]

#### Mensagens

Na seção anterior, tínhamos:

> [...] Isso também nos restringe de construções como `if`s, `while`s, e seus semelhantes, uma vez que não se dão como mensagens / métodos de um objeto. [...]

Confesso que raramente vejo darem a devida ênfase ao conceito de passagem de mensagens ao se ensinar *POO*. E assim, programas que se propõem a ser *OO* devem executar computações somente fazendo com que os objetos se comuniquem uns com os outros por meio da passagem de mensagens–por isso a história de cada objeto deve ser inteiramente auto-contido, expondo um conjunto bem definido de operações–e isso, inclusive, é um dos fatores responsáveis por trazer um dos, ao meu ver, maiores ganhos da *POO*: a **modularidade**. 

Então, como não vi aqui descrito na ementa, achei válido lembrar: por mais que não dê pra ilustrar ao longo do curso com alguma linguagem onde isso realmente ocorra, como alguma implementação de Smalltalk ([Squeak](http://squeak.org/), [Pharo](http://pharo.org/), [GNU Smalltalk](http://smalltalk.gnu.org/) etc.), de [Self](http://www.selflanguage.org/) ou de [IO](http://iolanguage.org/), acho válido mencionar pra turma.

#### Dynamic Dispatch

Como vimos na definição anterior, *dynamic dispatch* é uma das coisas mais importante na POO, uma vez que nos permite escrever código genérico em cima de uma interface, ao invés de baseados em características de um valor específico. Isso é muito importante quando se considera unidades de código modulares–ex.: uma função que filtre qualquer tipo de coleção; coleções têm as formas mais variadas de armazenar seus valores, e não é possível usar polimorfismo paramétrico para lidar com este caso. Graças a *dynamic dispatch*, você pode, em vez disso, escrever vários cálculos diferentes–um para cada valor–e selecionar, em tempo de execução, entre eles, dependendo do valor da coleção.

#### **Prototype-Based** *vs* **Class-Based**

Temos, na ementa:

> [...]
    5. **Classe**, Instância de Objetos.
    [...]

O que me leva a crer–juntamente com a escolha de Java como linguagem–, que a abordagem será **Class-Based**. Contudo, meu receio é que classes sejam apresentadas como sendo um conceito o qual *OO* implica, esquecendo-se de modelos, como a herança baseada em protótipos, visto em linguagens como [JS](https://www.ecma-international.org/publications/standards/Ecma-262.htm), [Self](http://www.selflanguage.org/) e [Slate](https://github.com/briantrice/slate-language). Assim como foi na minha cadeira de *POO*, muitas vezes nem se é apresentado outros modelos de herança, quando, na verdade, há casos que podemos implementar coisas de maneira ainda mais elegante com estes, vide: [SELF: The Power of Simplicity](http://bibliography.selflanguage.org/_static/self-power.pdf) e [Organizing Programs Without Classes](http://bibliography.selflanguage.org/_static/organizing-programs.pdf).

#### Polimorfismo

Ok, temos:

> [...]
    9. Abstração, Herança e Polimorfismo.
    [...]

E vi que polimorfismo está aí–então, provavelmente, nem seria necessário eu levantar esse tópico–mas, inclusive quando fui pagar minha cadeira de *POO*, tudo de polimorfismo visto foi muito superficial e acabei não vendo muitas formas de polimorfismo–e as que vi, foram de maneira insuficiente–então achei válido ressaltar a importância de se trazer bem os quatro mais difundidos:

- **Paramétrico**: Já que está dando Java, *Generics* poderiam ser uma boa.
- **Subtipagem**/*de Inclusão*: Esse dificilmente é deixado de fora então nem precisa eu lembrar.
- **Sobrecarga**: Explicando que, no caso de Java, há suporte a sobrecarga de métodos se os operandos têm diferentes tipos e/ou aridades.
- **de Coerção**: Com Java, o que eu vejo de exemplo seria algo como o que acontece com o empacotamento de primitivos ou quando há concatenação, por exemplo, de uma String com um primitivo.

Mas além desses, seria válido ao menos mencionar outras formas também comuns de polimorfismo–afinal, mesmo que não dê pra se aprofundar, pelo menos para saberem da existência e irem atrás:

- **Higher-Kinded**: Ok, esse talvez seja um pouco mais complicado de se exemplificar com langs OO, mas mencionar como se dá isso em *Scala*, por exemplo é válido–até porque eles já vão estar brincando com uma linguagem da *JVM*, por que não duas logo?
- **Estrutural**: Quando tive minha cadeira de *POO*, também com *Java*, acabamos vendo–bem por cima–interfaces, mas nunca nos foi mencionado como isso poderia se comportar como polimorfismo estrutural–mas, novamente, ilustrar esse com *Scala* pode ser bem mais interessante.

> Sim, caberia vários outros tipos de polimorfismo aqui, mas não sei exatamente o quão abrangente é o escopo do curso, então fica nesses mesmo.

#### Outra API de UI

Vi aqui que é pretendido usar *Swing*:

> [...]
    19. Componentes básicos do Swing
    20. Lista 6 - Janelas.    
    [...]

Assim, meu conhecimento de *Swing*–e de APIs Java em geral–é bem escasso, o único contato que tive foi na famigerada cadeira de *POO*. Mas ele me pareceu bem **limitado** e ainda **desatualizado**. Me pergunto se usar algo como o [JavaFX](http://docs.oracle.com/javase/8/javafx/get-started-tutorial/jfx-overview.htm#JFXST784), [SWT](http://www.eclipse.org/swt/), [Qt Jambi](http://qtjambi.org/) etc. não seria melhor.

---

Enfim, aqui foram apenas alguns pontos. Depois, se eu me lembrar de mais também levanto aqui. Não sei o quão aplicáveis são, pois não sei o estágio do curso nem se você concordaria, mas achei válido levantar a discussão mesmo assim 😄

**Comment by jefponte** [comment]
Olá, 
Obrigado pela interação e pelas contribuições. 
O curso está no começo, acabamos de ter a primeira aula na semana passada e abordamos apenas lógica de programação em java, falando da máquina virtual, variáveis primitivas, estruturas de fluxo e laços. Não entramos ainda na Orientação a Objetos em si. 

Os pontos que você levantou são muito importantes e agradeço também pelas fontes que você lincou. Com certeza levaremos em conta todas esses pontos ao ministrar as aulas que se seguirão, principalmente na parte de definição de Objeto e Classe, no enfoque da chamada de métodos como envio de mensagens a objetos. 

Sobre a parte de GUI vou mencionar sim essas que você falou, mas nós iremos ensinar mesmo a utilização dos componentes da biblioteca do Swing por conta das minhas limitações de conhecimento mesmo. Quem sabe no próximo curso a gente faz com QT. Nem é o foco deste curso o ensino da biblioteca em si, apenas faremos uso delas para reforçar os conhecimentos ensinados de Orientação a Objetos. Por exemplo: criando uma classe e herdando JFrame e fazendo sobrescrita de métodos. 

Sinta-se a vontade para levantar mais pontos, outras discussões, nos enviar fontes bibliográficas e listas de exercícios. Você está contribuindo para uma mundo com melhores programadores.

**Comment by ythecombinator** [comment]
Poxa, cara, realmente valeuzão pela recepção e, novamente, parabéns pela maneira como tem conduzido.

Acabei encontrando uma *"issue na minha issue"* que foi: 

>  São tipos primitivos que são–a partir do Java 5, salvo engano meu–automaticamente encapsulados; ou seja, convertidos em suas respectivas "forma de objeto", quando você interage com eles.

Isso, na verdade, se dá em runtime.

No mais, vamos dando nossas parcelas aí de contribuição 😄
